### PR TITLE
include includeDerivedMembership option for group sync

### PR DESCRIPTION
**Pull request by eduardomazolini**
In command:
gam course xxx sync students|teachers group yyyy@ddddd.ddd.dd
I add alternative option "group_inde" (INclude DErived). Just a sugestion name, be free for change.
gam course xxx sync students|teachers group_inde yyyy@ddddd.ddd.dd

### CODE REVIEW

**Comment by eduardomazolini** [comment]
I was trying to create a recursive function, when debugging, I saw the option in the documentation.
Now I also saw that one of the existing functions has this option as the last parameter.
Instead of creating an option with a strange name how about changing to an option at the end?

**Comment by taers232c** [comment]
Eduardo,

includeDerivedMembership does not work as you expect; yes, it returns the users from the embedded groups but it also returns the groups themselves.
```
$ gam print group-members group testgroup1
Getting members for testgroup1@domain.com (1/1)
group,id,email,role,type,status
testgroup1@domain.com,100763751091086757711,admin@domain.com,OWNER,USER,ACTIVE
testgroup1@domain.com,02et92p00o704lb,testgroup2@domain.com,MEMBER,GROUP,ACTIVE
testgroup1@domain.com,118080758787650801331,testuser1@domain.com,MEMBER,USER,ACTIVE
testgroup1@domain.com,107344800159717682514,testuser2@domain.com,MEMBER,USER,ACTIVE
testgroup1@domain.com,109097381978066352282,testuser3@domain.com,MEMBER,USER,ACTIVE

$ gam print group-members group testgroup1 includederivedmembership
Getting members for testgroup1@domain.com (1/1)
group,id,email,role,type,status
testgroup1@domain.com,116126129626858888856,testuser4@domain.com,MEMBER,USER,ACTIVE
testgroup1@domain.com,02et92p00o704lb,testgroup2@domain.com,MEMBER,GROUP,ACTIVE
testgroup1@domain.com,114925742703179281438,testuser7@domain.com,MEMBER,USER,ACTIVE
testgroup1@domain.com,106003875779405359392,testuser5@domain.com,MEMBER,USER,ACTIVE
testgroup1@domain.com,118080758787650801331,testuser1@domain.com,MEMBER,USER,ACTIVE
testgroup1@domain.com,109097381978066352282,testuser3@domain.com,MEMBER,USER,ACTIVE
testgroup1@domain.com,107344800159717682514,testuser2@domain.com,MEMBER,USER,ACTIVE
testgroup1@domain.com,100763751091086757711,admin@domain.com,OWNER,USER,ACTIVE
```

I've addressed this in Advanced GAM with an option that supplies just the user members.
```
group_users|group_users_ns|group_users_susp <GroupList>
        [members] [managers] [owners]
        [primarydomain] [domains <DomainNameList>] [recursive] end
```

**Comment by eduardomazolini** [comment]
taers232c,

This is not a problem, its will filter.

https://github.com/eduardomazolini/GAM/blob/c60947a8b27822e102f3d538f0f9d8dd4a8c1dbc/src/gam/__init__.py#L12167


> Eduardo,
> 
> includeDerivedMembership does not work as you expect; yes, it returns the users from the embedded groups but it also returns the groups themselves.
> 
> ```
> $ gam print group-members group testgroup1
> Getting members for testgroup1@domain.com (1/1)
> group,id,email,role,type,status
> testgroup1@domain.com,100763751091086757711,admin@domain.com,OWNER,USER,ACTIVE
> testgroup1@domain.com,02et92p00o704lb,testgroup2@domain.com,MEMBER,GROUP,ACTIVE
> testgroup1@domain.com,118080758787650801331,testuser1@domain.com,MEMBER,USER,ACTIVE
> testgroup1@domain.com,107344800159717682514,testuser2@domain.com,MEMBER,USER,ACTIVE
> testgroup1@domain.com,109097381978066352282,testuser3@domain.com,MEMBER,USER,ACTIVE
> 
> $ gam print group-members group testgroup1 includederivedmembership
> Getting members for testgroup1@domain.com (1/1)
> group,id,email,role,type,status
> testgroup1@domain.com,116126129626858888856,testuser4@domain.com,MEMBER,USER,ACTIVE
> testgroup1@domain.com,02et92p00o704lb,testgroup2@domain.com,MEMBER,GROUP,ACTIVE
> testgroup1@domain.com,114925742703179281438,testuser7@domain.com,MEMBER,USER,ACTIVE
> testgroup1@domain.com,106003875779405359392,testuser5@domain.com,MEMBER,USER,ACTIVE
> testgroup1@domain.com,118080758787650801331,testuser1@domain.com,MEMBER,USER,ACTIVE
> testgroup1@domain.com,109097381978066352282,testuser3@domain.com,MEMBER,USER,ACTIVE
> testgroup1@domain.com,107344800159717682514,testuser2@domain.com,MEMBER,USER,ACTIVE
> testgroup1@domain.com,100763751091086757711,admin@domain.com,OWNER,USER,ACTIVE
> ```
> 
> I've addressed this in Advanced GAM with an option that supplies just the user members.
> 
> ```
> group_users|group_users_ns|group_users_susp <GroupList>
>         [members] [managers] [owners]
>         [primarydomain] [domains <DomainNameList>] [recursive] end
> ```

**Comment by taers232c** [comment]
It will not filter; groupUserMembersOnly=False turns off the filter
```
def doUpdateGroup():
....
	elif myarg == 'sync':
            syncMembersSet = set()
            syncMembersMap = {}
            role, users_email, delivery = _getRoleAndUsers()
            for user_email in users_email:
		if user_email in ('*', GC_Values[GC_CUSTOMER_ID]):
                    syncMembersSet.add(GC_Values[GC_CUSTOMER_ID])
                else:
                    syncMembersSet.add(
                        _cleanConsumerAddress(user_email.lower(),
                                              syncMembersMap))
            group = checkGroupExists(cd, group)
            if group:
		currentMembersSet = set()
                currentMembersMap = {}
                for current_email in getUsersToModify(
                        entity_type='group',
                        entity=group,
                        member_type=role,
                        groupUserMembersOnly=False):
                    if current_email == GC_Values[GC_CUSTOMER_ID]:
                        currentMembersSet.add(current_email)
                    else:
                        currentMembersSet.add(
                            _cleanConsumerAddress(current_email.lower(),
                                                  currentMembersMap))
```

**Comment by taers232c** [comment]
Look at your lines: 8751-8770, groupUserMembersOnly=False in the call to getUsersToModify
```
         elif myarg == 'sync':
            syncMembersSet = set()
            syncMembersMap = {}
            role, users_email, delivery = _getRoleAndUsers()
            for user_email in users_email:
                if user_email in ('*', GC_Values[GC_CUSTOMER_ID]):
                    syncMembersSet.add(GC_Values[GC_CUSTOMER_ID])
                else:
                    syncMembersSet.add(
                        _cleanConsumerAddress(user_email.lower(),
                                              syncMembersMap))
            group = checkGroupExists(cd, group)
            if group:
                currentMembersSet = set()
                currentMembersMap = {}
                for current_email in getUsersToModify(
                        entity_type='group',
                        entity=group,
                        member_type=role,
                        groupUserMembersOnly=False):
                    if current_email == GC_Values[GC_CUSTOMER_ID]:
                        currentMembersSet.add(current_email)
                    else:
                        currentMembersSet.add(
                            _cleanConsumerAddress(current_email.lower(),
                                                  currentMembersMap))
```
Look at your lines 12164-12169, when groupUserMembersOnly is False, the filter is skipped.
```
        users = []
        for member in members:
            if ((not groupUserMembersOnly) or
                (member['type'] == 'USER')) and _checkMemberRoleIsSuspended(
                    member, validRoles, checkSuspended):
```

**Comment by taers232c** [comment]
You could change line 12166:
```
if ((not groupUserMembersOnly and not includeDerivedMembership) or
```

**Comment by eduardomazolini** [comment]
> Look at your lines: 8751-8770, groupUserMembersOnly=False in the call to getUsersToModify
> 
> ```
>          elif myarg == 'sync':
>             syncMembersSet = set()
>             syncMembersMap = {}
>             role, users_email, delivery = _getRoleAndUsers()
>             for user_email in users_email:
>                 if user_email in ('*', GC_Values[GC_CUSTOMER_ID]):
>                     syncMembersSet.add(GC_Values[GC_CUSTOMER_ID])
>                 else:
>                     syncMembersSet.add(
>                         _cleanConsumerAddress(user_email.lower(),
>                                               syncMembersMap))
>             group = checkGroupExists(cd, group)
>             if group:
>                 currentMembersSet = set()
>                 currentMembersMap = {}
>                 for current_email in getUsersToModify(
>                         entity_type='group',
>                         entity=group,
>                         member_type=role,
>                         groupUserMembersOnly=False):
>                     if current_email == GC_Values[GC_CUSTOMER_ID]:
>                         currentMembersSet.add(current_email)
>                     else:
>                         currentMembersSet.add(
>                             _cleanConsumerAddress(current_email.lower(),
>                                                   currentMembersMap))
> ```
> 
> Look at your lines 12164-12169, when groupUserMembersOnly is False, the filter is skipped.
> 
> ```
>         users = []
>         for member in members:
>             if ((not groupUserMembersOnly) or
>                 (member['type'] == 'USER')) and _checkMemberRoleIsSuspended(
>                     member, validRoles, checkSuspended):
> ```

**Comment by eduardomazolini** [comment]
> You could change line 12166:
> 
> ```
> if ((not groupUserMembersOnly and not includeDerivedMembership) or
> ```

Ok, if you have more experience, this is suggesting I don't see why not.

**Pull request merged**
