### PR TITLE
Changes to atom/service.py and gdata/service.py to support Domain Shared Contacts

### PR DESCRIPTION
**Pull request by taers232c**
Google Domain Shared Contacts requires 'GData-Version': '3.0'. These two changes support making this specification through additional_headers.
atom/service.py hardcoded 'GData-Version': '2.0'. The change only sets that value if GData-Version is not already present in additional_headers.
gdata/service.py now passes additional_headers to AtomService.__init__

### CODE REVIEW

**Comment by brainysmurf** [comment]
How does passing additional_headers to its parent class make a difference, as it is just set (in the same exact way) in the child class? (GDataService is a subclass of AtomService)

**Comment by taers232c** [comment]
You're right, only the atom/service.py change is required.

Thanks

**Comment by brainysmurf** [comment]
Curious why are those packages being changed to accommodate? It's more portable if you override the classes. (Sorry for all the questions, I'd really like to help make gam even more awesome.)

**Comment by taers232c** [comment]
If you look at the Google atom distribution, the "all_headers['GData-Version'] = '2.0'" statement is not there; it got added in somewhere along the line in Jay's version, I suppose to solve some problem where GData-Version needed to be explicitly set. My solution lets you override the value when necessary and otherwise forces the value to 2.0 as in the current version. Why should GAM have to override the class to get around a vestigial coding issue in an already customized version?

**Comment by brainysmurf** [comment]
From where I'm sitting, it's better to customise packages via programable hooks (such as overriding classes), instead of copying and then customising. That means more code to maintain. But at least I understand where this is coming from now, thanks.

**Comment by jay0lee** [comment]
I'm actively trying to get rid of the gdata / atom / XML libraries in GAM to simplify the codebase. XML is big fat and ugly IMHO. I know there are things it can do that JSON can't but for the Google APIs, JSON makes for a much easier dev experience.

Unfortunately it's taking Google a while to replace all of the GData APIs with Google API equivalents.

So I guess I'm ok with accepting Domain Shared Contacts GData commands into GAM as long as they aren't to invasive but I hope to see them replaced with Google API equivalents as soon as a Google API version of Contacts ships.

Regarding where to fix the GData header, Adam's right on principal but the atom / gdata libraries are already hacked up pretty well anyway. I removed all the libraries that were not GAM specific (including contacts which I assume Ross will add back in eventually).

Let's keep this patch in atom so that when atom goes away, it goes away also.

Jay

**Pull request merged**
