### PR TITLE
Pyupgrade --py37-plus

### PR DESCRIPTION
**Pull request by janosh**
Noticed that even though this repo specifies some pre-commit hooks, looks like they haven't been applied to parts of the code.

Happy to add changes from the other hooks to this PR as well. Can also open a new one to keep this one manageable.

### CODE REVIEW

**Comment by janosh** [comment]
Just saw that this PR conflicted quite a bit. I rebased onto `upstream/main` and in light of https://github.com/jay0lee/GAM/commit/a9f0e5ba163b7eedfe7c23402123f7489318cea5 applied `pyupgrade --py37-plus **/*.py`.

**Comment by jay0lee** [comment]
I don't see anything specific to pre-commit in the files changed? Can we hold on the python37 changes and do that as a separate commit?

**Comment by janosh** [comment]
I just dropped the changes created by  `pre-commit run yapf -a` and changed the title of this PR to reflect that it's now about `pyupgrade`. Just didn't rename the branch to avoid hassle but essentially the old PR is dead.

> Can we hold on the python37 changes?

Sure. Do you still want the `pre-commit` changes? Can create a new PR.

**Review by devilshezi0 — APPROVED** [review]

**Review by devilshezi0 — APPROVED** [review]

**Review by devilshezi0 — APPROVED** [review]
c3ddeae3f35be646ce9cb471ba4ade072343be1d

**Comment by devilshezi0** [comment]
c3ddeae3f35be646ce9cb471ba4ade072343be1d

**Review by devilshezi0 — APPROVED** [review]

**Comment by devilshezi0** [comment]
> Noticed that even though this repo specifies some pre-commit hooks, looks like they haven't been applied to parts of the code.
> 
> Happy to add changes from the other hooks to this PR as well. Can also open a new one to keep this one manageable.

**Pull request merged**
