### PR TITLE
Add inter_batch_wait

### PR DESCRIPTION
**Pull request by taers232c**
Can we go ahead and enter this now to give sync users a solution that works with gam batch and does paced adds/remove. Nothing prevents the users from doing: gam csv 1000users.csv gam update group oldgam add member ~email

### CODE REVIEW

**Comment by jay0lee** [comment]
I don't see the point of adding further complexity when batch API calls is slower than parallel API calls. Can we look at re-implementing with parallel API calls?

**Comment by taers232c** [comment]
Parallel add/removes have not been eliminated, you can still do that if you want.
What batch does is speeds up: gam update group group@domain.com <mailto:group@domain.com> add/remove/sync member <ou /Path/To/OU, file FileName, ...>

--
ross.scroggs@gmail.com

**Comment by jay0lee** [comment]
but it's not actually faster than parallel. I'm looking at re-implementing add/remove/sync to use parallel.

**Comment by taers232c** [comment]
You have to update your school groups every night to allow for new students/departing students.
On the first day of school, batch may be somewhat slow that parallel, but on every other night you pay a big price.
Batch:
gam update group seniors@domain.com <mailto:seniors@domain.com> sync members ou /Students/ClassOf2018

or 

Parallel:
gam update group seniors@domain.com <mailto:seniors@domain.com> clear member
echo "primaryEmail" > users.csv
gam ou /Students/ClassOf2018 print >> users.csv
gam csv users.csv gam update group seniors@domain.com <mailto:seniors@domain.com> add member ~primaryEmail
--
ross.scroggs@gmail.com

**Comment by jay0lee** [comment]
See my commit just now to switch to using parallel instead of batch for add/remove/sync. It still needs some cleanup but I'm going to stick with parallel unless you can convince me that batch is either faster or simpler.

**Pull request closed without merging**
