### PR TITLE
Implement appdirs, cleanup for pylint

### PR DESCRIPTION
**Pull request by taers232c**
1) Implement use of appdirs.py to specify config file/cache directories with alternate use of environment variables.
2) Many minor changes to keep pylint/pyflakes happy; incorrect spacing, incorrect indentation, trailing spaces, redefinition of built-ins, unused variables, ...
3) Define GAM_AUTOBATCH environment variable to control use of batch when multiple users are defined
4) Prevent gam all users print and gam all cros print from running a batch
5) Add ascending/descending/orderby arguments to gam print printjobs
6) Add selection arguments to gam printjob id fetch
7) Enhance gam print cros to allow more control of output
8) Fix backgroundcolor/foregroundcolr processing in gam ... add/update calendar

### CODE REVIEW

**Comment by jay0lee** [comment]
Awesome, thanks Ross,

Can you resubmit the non-appdirs changes as a separte pull request and I'll go ahead and accept them? I know I've been part of the problem with these but going forward, smaller requests are preferable.

Regarding the appdir changes, I'd like to reduce the dependency on environment variables rather than increase it. Ideally we'd be adding no new environment variables but allow existing ones to override appdir for legacy reasons.

The reason I'm pushing to phase out env. variables is that GAM itself can't set them. I'd like to eventually have a command like "gam config" available that allows admins to toggle all these settings via a minimal UI rather than needing to know to set some env. variable (a command which differs based on your OS).

Again, thanks for getting something together so quick and sorry to be a pain about it.

Jay

**Comment by taers232c** [comment]
Jay,

I removed the appdirs stuff; it got scarier and scarier as the default as the night went on.
I left in the environment variable stuff: GAMSITECONFIGDIR, GAMUSERCONFIGDIR, GAMCACHEDIR, GAMDRIVEDIR, GAMCLIENTSECRETSFILE
With these, someone could use an alternative config/cache file scheme if they'd like.

Ross

**Comment by taers232c** [comment]
Jay,

I removed the appdirs stuff which seems to have updated the pull request; can you verify that?.

I'm new to GitHub, bear with me.

Ross

--
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Jay,

Here's a thought about the future on how to move away from environment
variables.
Suppose we make a simple config file gam.cfg (whatever) that is simple a
list of key value pairs where the keys are the equivalent to the current
environment variables.
<<<
# This a comment
domain=bar.com
customer_id=12234
gam_threads=5
oauthfile=c:\gamstuff\oauth2.txt
...
>>>
Gam looks for this somewhere, maybe at its feet, or with appdirs, but it
gets one somehow and off gam goes.
Suppose you have multiple configs, not a problem: gam config filename users
org Staff show profile
Suppose you want to override some options: gam options key value ...
options users org Staff show profile
(Its options k v k v ... options so its obvious when you're done.
Combine the two: gam config filename options k v k v options users org
Staff show profile

gam [config <Filename>] [options (<Key> <Value>|default)* options] <Normal
gam arguments including batch csv whatever>

config and options don't interfere with any current commands/arguments so
nothing should break by adding this.

Then the program you imagined to update the config is:
gamopts [config <Filename>] [options (<Key> <Value>|default)* options]
[print]

That's the basics. But wait, there's more!
For those people supporting multiple customers/domains/whatever, we
introduce sections.

<<<
# Values for everyone, defaults
gam_threads 5
client_secrets c:\gamstuff\client_secrets.json
[Customer1]
# Customer1 is arbitrary
oauthfile c:\gamstuff\cust1\oauth2.txt
oauth2service c:\gamstuff\cust1\oauth2service
[AnotherCustomer]
# AnotherCustomer is just as arbitrary as Customer1
oauthfile c:\gamstuff\acust\oauth2.txt
oauth2service c:\gamstuff\acust\oauth2service
>>

Now we have:
gam [config <Filename>] [customer <String>] [options (<Key>
<Value>|default)* options] <Normal gam arguments including batch csv
whatever>
gamopts [config <Filename>] [customer <String>] [options (<Key>
<Value>|default)* options] [print]

So the process is:
1) Get the default or specified config file and read all values up to first
customer section, all unspecified values are set to their default
2) If a customer is specified, read all values in that section overriding
the values from step 1
3) If options are specified, <Key> <Value> does the obvious, <Key> default
overrides the customer value from step 2 with the value from step 1

Does this make sense? If so, I'd be quite willing to bang it out.

Ross

On Thu, Aug 20, 2015 at 8:28 AM, Jay Lee <notifications@github.com> wrote:

> Merged #99 <https://github.com/jay0lee/GAM/pull/99>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jay0lee/GAM/pull/99#event-387804913>.
>



-- 
Ross Scroggs
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Jay,

And most of the work seems to be already done:
https://docs.python.org/2/library/configparser.html

Ross

On Thu, Aug 20, 2015 at 1:04 PM, Ross Scroggs <ross.scroggs@gmail.com>
wrote:

> Jay,
>
> Here's a thought about the future on how to move away from environment
> variables.
> Suppose we make a simple config file gam.cfg (whatever) that is simple a
> list of key value pairs where the keys are the equivalent to the current
> environment variables.
> <<<
> # This a comment
> domain=bar.com
> customer_id=12234
> gam_threads=5
> oauthfile=c:\gamstuff\oauth2.txt
> ...
> >>>
> Gam looks for this somewhere, maybe at its feet, or with appdirs, but it
> gets one somehow and off gam goes.
> Suppose you have multiple configs, not a problem: gam config filename
> users org Staff show profile
> Suppose you want to override some options: gam options key value ...
> options users org Staff show profile
> (Its options k v k v ... options so its obvious when you're done.
> Combine the two: gam config filename options k v k v options users org
> Staff show profile
>
> gam [config <Filename>] [options (<Key> <Value>|default)* options] <Normal
> gam arguments including batch csv whatever>
>
> config and options don't interfere with any current commands/arguments so
> nothing should break by adding this.
>
> Then the program you imagined to update the config is:
> gamopts [config <Filename>] [options (<Key> <Value>|default)* options]
> [print]
>
> That's the basics. But wait, there's more!
> For those people supporting multiple customers/domains/whatever, we
> introduce sections.
>
> <<<
> # Values for everyone, defaults
> gam_threads 5
> client_secrets c:\gamstuff\client_secrets.json
> [Customer1]
> # Customer1 is arbitrary
> oauthfile c:\gamstuff\cust1\oauth2.txt
> oauth2service c:\gamstuff\cust1\oauth2service
> [AnotherCustomer]
> # AnotherCustomer is just as arbitrary as Customer1
> oauthfile c:\gamstuff\acust\oauth2.txt
> oauth2service c:\gamstuff\acust\oauth2service
> >>
>
> Now we have:
> gam [config <Filename>] [customer <String>] [options (<Key>
> <Value>|default)* options] <Normal gam arguments including batch csv
> whatever>
> gamopts [config <Filename>] [customer <String>] [options (<Key>
> <Value>|default)* options] [print]
>
> So the process is:
> 1) Get the default or specified config file and read all values up to
> first customer section, all unspecified values are set to their default
> 2) If a customer is specified, read all values in that section overriding
> the values from step 1
> 3) If options are specified, <Key> <Value> does the obvious, <Key> default
> overrides the customer value from step 2 with the value from step 1
>
> Does this make sense? If so, I'd be quite willing to bang it out.
>
> Ross
>
> On Thu, Aug 20, 2015 at 8:28 AM, Jay Lee <notifications@github.com> wrote:
>
>> Merged #99 <https://github.com/jay0lee/GAM/pull/99>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jay0lee/GAM/pull/99#event-387804913>.
>>
>
>
>
> --
> Ross Scroggs
> ross.scroggs@gmail.com
>



-- 
Ross Scroggs
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Jay,

I'm almost finished, give me a day and Gam 3.52 will have one config file
and no environment variables.

Ross

On Thu, Aug 20, 2015 at 1:20 PM, Ross Scroggs <ross.scroggs@gmail.com>
wrote:

> Jay,
>
> And most of the work seems to be already done:
> https://docs.python.org/2/library/configparser.html
>
> Ross
>
> On Thu, Aug 20, 2015 at 1:04 PM, Ross Scroggs <ross.scroggs@gmail.com>
> wrote:
>
>> Jay,
>>
>> Here's a thought about the future on how to move away from environment
>> variables.
>> Suppose we make a simple config file gam.cfg (whatever) that is simple a
>> list of key value pairs where the keys are the equivalent to the current
>> environment variables.
>> <<<
>> # This a comment
>> domain=bar.com
>> customer_id=12234
>> gam_threads=5
>> oauthfile=c:\gamstuff\oauth2.txt
>> ...
>> >>>
>> Gam looks for this somewhere, maybe at its feet, or with appdirs, but it
>> gets one somehow and off gam goes.
>> Suppose you have multiple configs, not a problem: gam config filename
>> users org Staff show profile
>> Suppose you want to override some options: gam options key value ...
>> options users org Staff show profile
>> (Its options k v k v ... options so its obvious when you're done.
>> Combine the two: gam config filename options k v k v options users org
>> Staff show profile
>>
>> gam [config <Filename>] [options (<Key> <Value>|default)* options]
>> <Normal gam arguments including batch csv whatever>
>>
>> config and options don't interfere with any current commands/arguments so
>> nothing should break by adding this.
>>
>> Then the program you imagined to update the config is:
>> gamopts [config <Filename>] [options (<Key> <Value>|default)* options]
>> [print]
>>
>> That's the basics. But wait, there's more!
>> For those people supporting multiple customers/domains/whatever, we
>> introduce sections.
>>
>> <<<
>> # Values for everyone, defaults
>> gam_threads 5
>> client_secrets c:\gamstuff\client_secrets.json
>> [Customer1]
>> # Customer1 is arbitrary
>> oauthfile c:\gamstuff\cust1\oauth2.txt
>> oauth2service c:\gamstuff\cust1\oauth2service
>> [AnotherCustomer]
>> # AnotherCustomer is just as arbitrary as Customer1
>> oauthfile c:\gamstuff\acust\oauth2.txt
>> oauth2service c:\gamstuff\acust\oauth2service
>> >>
>>
>> Now we have:
>> gam [config <Filename>] [customer <String>] [options (<Key>
>> <Value>|default)* options] <Normal gam arguments including batch csv
>> whatever>
>> gamopts [config <Filename>] [customer <String>] [options (<Key>
>> <Value>|default)* options] [print]
>>
>> So the process is:
>> 1) Get the default or specified config file and read all values up to
>> first customer section, all unspecified values are set to their default
>> 2) If a customer is specified, read all values in that section overriding
>> the values from step 1
>> 3) If options are specified, <Key> <Value> does the obvious, <Key>
>> default overrides the customer value from step 2 with the value from step 1
>>
>> Does this make sense? If so, I'd be quite willing to bang it out.
>>
>> Ross
>>
>> On Thu, Aug 20, 2015 at 8:28 AM, Jay Lee <notifications@github.com>
>> wrote:
>>
>>> Merged #99 <https://github.com/jay0lee/GAM/pull/99>.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/jay0lee/GAM/pull/99#event-387804913>.
>>>
>>
>>
>>
>> --
>> Ross Scroggs
>> ross.scroggs@gmail.com
>>
>
>
>
> --
> Ross Scroggs
> ross.scroggs@gmail.com
>



-- 
Ross Scroggs
ross.scroggs@gmail.com

**Comment by brainysmurf** [comment]
Hi guys,

I saw the comment about not wishing to use environment variables, and was going to suggest configparse. Glad you found it yourselves. The common naming convention is often settings.ini, and it makes a lot of sense to be able to specify multiple domains in there too. Something like:

domain_first
api_key: 0123456789

domain_second
api_key: 9876543210

gam domain first
It does what it needs to do to use the first settings for consecutive runs.

Adam

**Pull request merged**
