### PR TITLE
Add a GAM command to invite a person to a course 

### LINKED ISSUE #1264: Add a GAM command to invite a person to a course
Please, add a GAM command to invite a person (as a student, teacher, or owner) to a course, so the person has the option to accept or decline the invite to the course.

### PR DESCRIPTION
**Pull request by ricardoseriani**
Add a GAM command to invite a person (as a student, teacher, or owner) to a course, so the person has the option to accept or decline the invite to the course.

Command description:
`gam course <CourseID> invite teachers|students|owners <UserItem>`

Closes #1264

### CODE REVIEW

**Comment by jay0lee** [comment]
Thanks for the PR! Couple questions we need to answer here:
- we need methods to list invitations as well as uninvite.
- what happens if an admin tries to directly add a student who has already been invited but not accepted? Makes above more important so admin can diagnose issue but would also be good to understand behavior.

**Comment by ricardoseriani** [comment]
>     * we need methods to list invitations as well as uninvite.
Good point.
Any recommendations on the syntax of the command?



>     * what happens if an admin tries to directly add a student who has already been invited but not accepted? Makes above more important so admin can diagnose issue but would also be good to understand behavior.

AFAIK, currently, if a person is invited as a student, and after that is added as a student, the person is 'automatticaly accepted' as a student, (an `add` has priority over an `invite`).

**Comment by taers232c** [comment]
Here's what Advanced GAM offers
* https://github.com/taers232c/GAMADV-XTD3/wiki/Classroom-Invitations

**Comment by ricardoseriani** [comment]
So, I should create a separate command for invitations, not use it as a subcommand for course?

And about uninvite, the only way that I found is by getting the `<invitation-id>`, but in that  case, I have to do 2 or more API requests, is that OK ?

**Comment by jay0lee** [comment]
closing this for now but feel free to re-open a PR with recommended fixes.

**Pull request closed without merging**
