### PR TITLE
Use patch instead of update in doUpdateCustomer

### PR DESCRIPTION
**Pull request by taers232c**

### CODE REVIEW

**Comment by jay0lee** [comment]
Was there a reason for this? For directory API alone update generally performs better in my testing. Not sure when user update switched back to patch but that should probably be set back to update as well. In general, we should not be using patch for Directory API.

**Comment by taers232c** [comment]
Yes. Update doesn't work.
```
With update
connect: (www.googleapis.com, 443)
send: 'PUT /admin/directory/v1/customers/xxx?alt=json&prettyPrint=true HTTP/1.1\r\nHost: www.googleapis.com\r\ncontent-length: 40\r\naccept-encoding: gzip, deflate\r\naccept: application/json\r\nuser-agent: GAM 4.40.00 - https://github.com/tae\
rs232c/GAMADV-X / Ross Scroggs <ross.scroggs@gmail.com> / Python 2.7.12 final / Darwin-15.6.0-x86_64-i386-64bit x86_64 / google-api-python-client/1.5.5 (gzip)\r\ncontent-type: application/json\r\nauthorization: Bearer \r\n\r\n{"postalAddress":\
 {"addressLine3": "x"}}'
reply: 'HTTP/1.1 503 Service Unavailable\r\n'
header: Vary: Origin
header: Vary: X-Origin
header: Content-Type: application/json; charset=UTF-8
header: Content-Encoding: gzip
header: Date: Wed, 21 Dec 2016 20:36:55 GMT
header: Expires: Wed, 21 Dec 2016 20:36:55 GMT
header: Cache-Control: private, max-age=0
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: SAMEORIGIN
header: X-XSS-Protection: 1; mode=block
header: Server: GSE
header: Alt-Svc: quic=":443"; ma=2592000; v="35,34"
header: Transfer-Encoding: chunked
send: 'PUT /admin/directory/v1/customers/xxx?alt=json&prettyPrint=true HTTP/1.1\r\nHost: www.googleapis.com\r\ncontent-length: 40\r\naccept-encoding: gzip, deflate\r\naccept: application/json\r\nuser-agent: GAM 4.40.00 - https://github.com/tae\
rs232c/GAMADV-X / Ross Scroggs <ross.scroggs@gmail.com> / Python 2.7.12 final / Darwin-15.6.0-x86_64-i386-64bit x86_64 / google-api-python-client/1.5.5 (gzip)\r\ncontent-type: application/json\r\nauthorization: Bearer \r\n\r\n{"postalAddress":\
 {"addressLine3": "x"}}'
reply: 'HTTP/1.1 503 Service Unavailable\r\n'
header: Vary: Origin
header: Vary: X-Origin
header: Content-Type: application/json; charset=UTF-8
header: Content-Encoding: gzip
header: Date: Wed, 21 Dec 2016 20:36:58 GMT
header: Expires: Wed, 21 Dec 2016 20:36:58 GMT
header: Cache-Control: private, max-age=0
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: SAMEORIGIN
header: X-XSS-Protection: 1; mode=block
header: Server: GSE
header: Alt-Svc: quic=":443"; ma=2592000; v="35,34"
header: Transfer-Encoding: chunked
```

```
With patch
connect: (www.googleapis.com, 443)
send: 'GET /discovery/v1/apis/admin/directory_v1/rest HTTP/1.1\r\nHost: www.googleapis.com\r\nif-none-match: "tbys6C40o18GZwyMen5GMkdK-3s/MJXmm78_R4W8L6tex9cqkPyvKmM"\r\naccept-encoding: gzip, deflate\r\nuser-agent: Python-httplib2/0.9.2 (gzip\
)\r\n\r\n'
reply: 'HTTP/1.1 304 Not Modified\r\n'
header: Expires: Wed, 21 Dec 2016 20:42:39 GMT
header: Date: Wed, 21 Dec 2016 20:37:39 GMT
header: Cache-Control: public, max-age=300, must-revalidate, no-transform
header: ETag: "tbys6C40o18GZwyMen5GMkdK-3s/MJXmm78_R4W8L6tex9cqkPyvKmM"
header: Vary: Origin
header: Vary: X-Origin
header: Server: GSE
header: Alt-Svc: quic=":443"; ma=2592000; v="35,34"
send: 'PATCH /admin/directory/v1/customers/xxx?alt=json&prettyPrint=true HTTP/1.1\r\nHost: www.googleapis.com\r\ncontent-length: 40\r\naccept-encoding: gzip, deflate\r\naccept: application/json\r\nuser-agent: GAM 4.40.00 - https://github.com/t\
aers232c/GAMADV-X / Ross Scroggs <ross.scroggs@gmail.com> / Python 2.7.12 final / Darwin-15.6.0-x86_64-i386-64bit x86_64 / google-api-python-client/1.5.5 (gzip)\r\ncontent-type: application/json\r\nauthorization: Bearer \r\n\r\n{"postalAddress\
": {"addressLine3": "x"}}'
reply: 'HTTP/1.1 200 OK\r\n'
header: Cache-Control: no-cache, no-store, max-age=0, must-revalidate
header: Pragma: no-cache
header: Expires: Mon, 01 Jan 1990 00:00:00 GMT
header: Date: Wed, 21 Dec 2016 20:37:40 GMT
header: ETag: "lC5l2xZhzgy1zYIWApDice-fN_A/MqPzM5498uOOdNdPJIkQIjsYo1M"
header: Vary: Origin
header: Vary: X-Origin
header: Content-Type: application/json; charset=UTF-8
header: Content-Encoding: gzip
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: SAMEORIGIN
header: X-XSS-Protection: 1; mode=block
header: Server: GSE
header: Alt-Svc: quic=":443"; ma=2592000; v="35,34"
header: Transfer-Encoding: chunked
Customer ID: xxx, Updated
```

**Comment by taers232c** [comment]
Any resolution here?

**Comment by jay0lee** [comment]
Not sure what happened here, looks like this was originally a single commit that just fixed the update vs patch (whcih is fine btw). But then you added a bunch of other non-related changes. Can we close and re-open or else reduce this PR to a single commit that fixes the patch vs. commit issue?

**Pull request closed without merging**
