### PR TITLE
os.environ, checkErrorCode, setGamDirs

### PR DESCRIPTION
**Pull request by brainysmurf**
- uses os.environ get() method instead of try/except. There is a performance penalty with exceptions and get() allows for defaults, which we are testing for anyway
- checkErrorCode is written a bit simpler and in a more pythonistic style for readability
- setGamDirs uses __file__ instead of sys args, making for more portability

### CODE REVIEW

**Comment by jay0lee** [comment]
Thanks for the PR @brainysmurf 

@taers232c can you try pulling it and see if all looks good? I know you're actively working on some of these areas.

**Comment by taers232c** [comment]
Jay,

Looks good to me; most of the os.path.join(...) stuff goes away with
gam.cfg but it's certainly cleaner in this version.
One correction on line 283:
Correct:

return u'%s - %s' % (e.error_code, error_code_map.get(e.error_code, u'Unknown
Error: %s' % (str(e))))

Incorrect:

return u'%s - %s' % (e.error_code, error_code_map.get(e.error_code, u'Unknown
Error: %s' % (e.error_code, str(e))))


Ross

On Fri, Oct 2, 2015 at 6:59 AM, Jay Lee <notifications@github.com> wrote:

> Thanks for the PR @brainysmurf <https://github.com/brainysmurf>
>
> @taers232c <https://github.com/taers232c> can you try pulling it and see
> if all looks good? I know you're actively working on some of these areas.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jay0lee/GAM/pull/123#issuecomment-145029519>.
>



-- 
Ross Scroggs
ross.scroggs@gmail.com

**Comment by jay0lee** [comment]
Thanks @taers232c ,

@brainysmurf if you can go ahead and make that change I'll commit this.

Jay

**Comment by brainysmurf** [comment]
How do you guys test with good code coverage? (I couldn't figure out how to test that bit directly.) Have you considered using the mock module?

**Comment by taers232c** [comment]
Adam,
These lines:
1300:  u'Entity %s exists' % e.invalidInput or '<unknown>',
need to look like this:
1300: u'Entity %s exists' % getattr(e, u'invalidInput', None) or u'<unknown>',

I'm seeing 1300 errors (OK with Contacts) where invalidInput is not a defined attribute.

Ross

**Comment by brainysmurf** [comment]
How do you test?

**Comment by taers232c** [comment]
In this particular case, the exception popped up in normal processing. Otherwise, I'm building a list of test cases that I run, some designed to force errors, others to make sure I haven't messed anything up.

**Comment by taers232c** [comment]
Clean slate!
--
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
See: no_browser.txt still needed by output_csv #157

--
ross.scroggs@gmail.com

**Pull request closed without merging**
