### PR TITLE
Increase todrive max cell count

### PR DESCRIPTION
**Pull request by taers232c**
https://support.google.com/drive/answer/37603?hl=en

### CODE REVIEW

**Comment by jay0lee** [comment]
Not that the docs are ever wrong (cough) but did you test this limit?

**Comment by taers232c** [comment]
Not directly. I have a user in Sweden where Gam wouldn't upload a file as a sheet because of the cell count limit; it was uploaded as a CSV file. He went into drive and successfully converted it to a sheet.
--
ross.scroggs@gmail.com

**Comment by jay0lee** [comment]
Can you test even with junk data not pulled from API? I feel like I tried to bump limit at one point and it failed to convert via API even though UI could.

Other option would be to remove limit, always yet convert and disable convert on retry if it fails with the limit error but that assumes limit failure returns a unique write and not something like a 5xx which would also need testing.

**Comment by taers232c** [comment]
Jay,

$ gam user admin print filelist fields appdatacontents,cancomment,canreadrevisions,capabilities,copyable,createddate,description,editable,explicitlytrashed,fileextension,filesize,foldercolorrgb,fullfileextension,headrevisionid,iconlink,id,lastmodifyinguser,lastmodifyingusername,lastviewedbyme,md5,mime,modifiedbyme,modifieddate fields name,originalfilename,ownedbyme,ownernames,owners,parents,quotabytesused,restricted,shareable,shared,sharedwithmedate,sharinguser,size,spaces,starred,thumbnaillink,title,trashed,userpermission,version,viewed,viewerscancopycontent,webcontentlink,webviewlink todrive tdtitle "AdminFiles"
Getting all Drive Files/Folders that match query ('me' in owners) for admin@rdschool.org
Got 460 Drive Files/Folders for admin@rdschool.org...
Got 920 Drive Files/Folders for admin@rdschool.org...
Got 1380 Drive Files/Folders for admin@rdschool.org...
Got 1840 Drive Files/Folders for admin@rdschool.org...
Got 2300 Drive Files/Folders for admin@rdschool.org...
Got 2760 Drive Files/Folders for admin@rdschool.org...
Got 3220 Drive Files/Folders for admin@rdschool.org...
Got 3680 Drive Files/Folders for admin@rdschool.org...
Got 4140 Drive Files/Folders for admin@rdschool.org...
Got 4600 Drive Files/Folders for admin@rdschool.org...
Got 5060 Drive Files/Folders for admin@rdschool.org...
Got 5520 Drive Files/Folders for admin@rdschool.org...
Got 5980 Drive Files/Folders for admin@rdschool.org...
Got 6440 Drive Files/Folders for admin@rdschool.org...
Got 6900 Drive Files/Folders for admin@rdschool.org...
Got 7360 Drive Files/Folders for admin@rdschool.org...
Got 7820 Drive Files/Folders for admin@rdschool.org...
Got 8149 Drive Files/Folders for admin@rdschool.org...
Rows: 8149, Columns: 75, Cells: 611175

Uploaded as sheet successfully.

Ross
--
ross.scroggs@gmail.com

**Comment by jay0lee** [comment]
I tested with 2m cells also and it works, go over that though and you hit an API error.

Can you remove the temp gam.py~ from this PR before I merge?

**Pull request merged**
