### PR TITLE
Improve CSV file reading

### PR DESCRIPTION
**Pull request by taers232c**
Open files with mode rU to help with cross platform issues.

Toss BOM that Windows puts at front of UTF encoded files.

Add optional argument [charset <Charset>] to gam csv to help users in non-English language countries.
gam csv <FileName> [charset <CharSet>] gam ...

### CODE REVIEW

**Comment by jay0lee** [comment]
The utf-8 commit should be one pull request and the doc update another since they're two different items. If they're two commits within a single PR I can only accept all or nothing. Sorry, just need to get some of this straightened out so we're not dealing with huge pull requests that lead to missed bugs.

**Comment by taers232c** [comment]
That's the part I'm not sure of; how to I make one commit on my part not merge with a previous pull request?
--
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Now CSV file handling only

**Comment by jay0lee** [comment]
Excellent, code looks good. Can you try squashing the commits? That makes the merge cleaner.

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Pull request closed without merging**
